import type { AppProps } from 'next/app';
import Head from 'next/head';
import { KbsProvider } from 'react-kbs';

import '../../tailwind.css';
import { ClientOnly } from '../components/ClientOnly';

export default function App(props: AppProps): JSX.Element {
  const { Component, pageProps } = props;

  return (
    <div>
      <Head>
        <title>League Team Creator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <KbsProvider>
        <ClientOnly>
          <Component {...pageProps} />
        </ClientOnly>
      </KbsProvider>
    </div>
  );
}
